import img1 from "/Gallery/img1.jpeg"
import img2 from "/Gallery/img2.jpeg"
import img3 from "/Gallery/img3.jpeg"
import img4 from "/Gallery/img4.jpeg"
import img5 from "/Gallery/img5.jpeg"
import img6 from "/Gallery/img6.jpeg"
import img7 from "/Gallery/img7.jpeg"
import img8 from "/Gallery/img8.jpeg"
import img9 from "/Gallery/img9.jpeg"
import img10 from "/Gallery/img10.jpeg"
import img11 from "/Gallery/img11.jpeg"
import Drinks1 from "/drinksImages/Drinks1.jpeg"
import Drinks2 from "/drinksImages/Drinks2.jpeg"
import Drinks3 from "/drinksImages/Drinks3.jpeg"
import Drinks4 from "/drinksImages/Drinks4.jpeg"
import Drinks5 from "/drinksImages/Drinks5.jpeg"
import Drinks6 from "/drinksImages/Drinks6.jpeg"
import Drinks7 from "/drinksImages/Drinks7.jpeg"
import Drinks8 from "/drinksImages/Drinks8.jpeg"
import Drinks9 from "/drinksImages/Drinks9.jpeg"
import Drinks10 from "/drinksImages/Drinks10.jpeg"
import Drinks11 from "/drinksImages/Drinks11.jpeg"
import Food1 from "/FoodImages/Food1.jpeg"
import Food2 from "/FoodImages/Food2.jpeg"
import Food3 from "/FoodImages/Food3.jpeg"
import Food4 from "/FoodImages/Food4.jpeg"
import Food5 from "/FoodImages/Food5.jpeg"
import Food6 from "/FoodImages/Food6.jpeg"
import Food7 from "/FoodImages/Food7.jpeg"
import Food8 from "/FoodImages/Food8.jpeg"
import Food9 from "/FoodImages/Food9.jpeg"
import Food10 from "/FoodImages/Food10.jpeg"
import Food11 from "/FoodImages/Food11.jpeg"


export const galleryImages = [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, Drinks1, Drinks2, Drinks3, Drinks4, Drinks5, Drinks6, Drinks7, Drinks8, Drinks9, Drinks10, Drinks11, Food1, Food2, Food3, Food4, Food5, Food6, Food7, Food8, Food9, Food10, Food11 ]